// lib/firebase_service.dart
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_database/firebase_database.dart';
import 'firebase_options.dart'; // <--- 1. ADD THIS IMPORT

// ✅ Your new, correct database URL is now here.
const String kDatabaseUrl = "https://oma-app-new-default-rtdb.firebaseio.com/";

class FirebaseService {
  FirebaseService._();
  static final FirebaseService instance = FirebaseService._();

  late final FirebaseApp app;

  Future<void> init() async {
    // 2. UPDATED THIS FUNCTION
    // We must pass the options generated by the CLI so Android knows about the SHA-1 key
    app = await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  }

  FirebaseAuth get auth => FirebaseAuth.instance;

  FirebaseDatabase get _db {
    if (kDatabaseUrl.isNotEmpty) {
      return FirebaseDatabase.instanceFor(app: app, databaseURL: kDatabaseUrl);
    }
    return FirebaseDatabase.instanceFor(app: app);
  }

  DatabaseReference userRef(String uid) => _db.ref('users/$uid');
  DatabaseReference notesRef(String uid) => _db.ref('notes/$uid');
  Query notesQuery(String uid) => notesRef(uid).orderByChild('createdAt');

  Future<UserCredential> signIn(String email, String password) {
    return auth.signInWithEmailAndPassword(email: email, password: password);
  }

  Future<void> signOut() => auth.signOut();

  Future<UserCredential> signUp({
    required String username,
    required String email,
    required String password,
  }) async {
    try {
      // Create user account
      final creds = await auth.createUserWithEmailAndPassword(
        email: email,
        password: password,
      );
      final user = creds.user!;

      // Update display name
      await user.updateDisplayName(username);

      // Send verification email
      await user.sendEmailVerification();
      
      // Debug logging
      print('User created successfully:');
      print('- UID: ${user.uid}');
      print('- Email: ${user.email}');
      print('- Email verified: ${user.emailVerified}');
      print('Verification email sent to: $email');

      // Store in Realtime Database with emailVerified = false
      await userRef(user.uid).set({
        'username': username,
        'email': email,
        'createdAt': ServerValue.timestamp,
        'emailVerified': false,
      });

      return creds;
    } catch (e) {
      print('Error during signup: $e');
      rethrow;
    }
  }

  // Resend verification email
  Future<void> resendVerificationEmail() async {
    try {
      final user = auth.currentUser;
      if (user != null && !user.emailVerified) {
        await user.sendEmailVerification();
        print('Verification email resent to: ${user.email}');
      }
    } catch (e) {
      print('Error resending verification email: $e');
      rethrow;
    }
  }

  // Check and update email verification status
  Future<bool> checkEmailVerification() async {
    try {
      final user = auth.currentUser;
      if (user != null) {
        // Reload user to get latest verification status
        await user.reload();
        final updatedUser = auth.currentUser!;
        
        print('Checking email verification:');
        print('- Email: ${updatedUser.email}');
        print('- Verified: ${updatedUser.emailVerified}');
        
        if (updatedUser.emailVerified) {
          // Update database when email is verified
          await userRef(updatedUser.uid).update({
            'emailVerified': true,
          });
        }
        
        return updatedUser.emailVerified;
      }
      return false;
    } catch (e) {
      print('Error checking email verification: $e');
      return false;
    }
  }

  // Debug method to check current user status
  Future<void> debugCheckUser() async {
    final user = auth.currentUser;
    if (user != null) {
      print('=== Current User Debug Info ===');
      print('UID: ${user.uid}');
      print('Email: ${user.email}');
      print('Email verified: ${user.emailVerified}');
      print('Display name: ${user.displayName}');
      print('Creation time: ${user.metadata.creationTime}');
      print('Last sign in: ${user.metadata.lastSignInTime}');
      print('==============================');
    } else {
      print('No current user signed in');
    }
  }

  Future<void> addNoteForCurrentUser(String text) async {
    final user = auth.currentUser!;
    final ref = notesRef(user.uid).push();
    await ref.set({
      'text': text,
      'createdAt': ServerValue.timestamp,
    });
  }

  Future<void> deleteNoteForCurrentUser(String noteKey) async {
    final user = auth.currentUser!;
    await notesRef(user.uid).child(noteKey).remove();
  }

  int timestampOf(DataSnapshot s) {
    final v = s.child('createdAt').value;
    if (v is int) return v;
    if (v is num) return v.toInt();
    return 0;
  }
}